name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.300
      - name: Build SignalR Lib
        run: dotnet build --configuration Release ./src/OrgnalR.SignalR
      - name: Build Orleans Lib
        run: dotnet build --configuration Release ./src/OrgnalR.OrleansSilo
