name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.x
      - name: Build SignalR Lib
        run: dotnet build --configuration Release ./src/OrgnalR.SignalR
      - name: Build Orleans Lib
        run: dotnet build --configuration Release ./src/OrgnalR.OrleansSilo
